server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Proxy for internal signals
    location /api/signals {
        proxy_pass http://trade_be:8081/signals;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy for tickers
    location /api/tickers {
        proxy_pass https://terminal-data.alrca.com/tickers;
        proxy_ssl_server_name on;
        proxy_set_header Host terminal-data.alrca.com;
    }

    # Proxy for candles
    location /api/candles {
        proxy_pass https://terminal-data.alrca.com/marketdata/candles;
        proxy_ssl_server_name on;
        proxy_set_header Host terminal-data.alrca.com;
    }

    # Proxy for news
    location /api/news {
        proxy_pass https://www.alphavantage.co/query;
        proxy_ssl_server_name on;
        proxy_set_header Host www.alphavantage.co;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}