kind: pipeline
type: docker
name: Development Pipeline Exec

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - development

node:
  env: dev

steps:
- name: deploy
  commands:
  - docker compose down && docker compose up -d --build

- name: docker clean
  commands:
  - docker system prune -a --volumes -f