kind: pipeline
type: exec
name: Development Pipeline Exec

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - development

node:
  env: dev

steps:
- name: docker build
  commands:
  -  docker build -t fake/bloomberg:latest .
- name: docker deploy
  commands:
  - docker stop bloomberg || true
  - docker rm --force bloomberg || true
  - docker run --restart=always --name=bloomberg -p 28081:8080 -d fake/bloomberg:latest